name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Runs at 10:30 AM IST (5:00 AM UTC) every day
    - cron: '00 05 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  setup:
    name: "Setup and Install Dependencies"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Install dependencies
      run: npm ci
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
    - name: Type check
      run: npm run typecheck

  test:
    name: "Test ${{ matrix.project-name }}"
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - project-name: "Project 1 - Example"
            project-id: "project-1-example"
            artifact-name: "project-1-playwright-report"
          - project-name: "Project 2 - Example 2" 
            project-id: "project-2-example-2"
            artifact-name: "project-2-playwright-report"
          - project-name: "Project 3 - Example 3"
            project-id: "project-3-example-3"
            artifact-name: "project-3-playwright-report"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    - name: Restore Playwright browsers cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
    - name: Run ${{ matrix.project-name }} Tests
      run: npx playwright test --project=${{ matrix.project-id }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.artifact-name }}
        path: playwright-report/
        retention-days: 30
