#!/usr/bin/env python3
"""
Test script to verify Gmail SMTP settings locally
Run this before setting up GitHub Actions to ensure your credentials work
"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def test_gmail_smtp():
    """Test Gmail SMTP connection and send a test email"""
    
    # Configuration - Update these with your details
    smtp_host = "smtp.gmail.com"
    smtp_port = 587
    username = input("Enter your Gmail address: ")
    password = input("Enter your Gmail App Password (16 chars): ")
    recipient = input("Enter recipient email (or press Enter to use same as username): ")
    
    if not recipient:
        recipient = username
    
    print(f"\n🔧 Testing Gmail SMTP connection...")
    print(f"Host: {smtp_host}:{smtp_port}")
    print(f"Username: {username}")
    print(f"Recipient: {recipient}")
    
    try:
        # Create test message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = "🧪 Gmail SMTP Test - GitHub Actions Setup"
        msg['From'] = username
        msg['To'] = recipient
        
        # Test HTML content
        html_content = """
        <html>
        <body>
            <h2>✅ Gmail SMTP Test Successful!</h2>
            <p>This email confirms that your Gmail SMTP settings are working correctly.</p>
            <p><strong>Next steps:</strong></p>
            <ul>
                <li>Add these settings to your GitHub repository secrets</li>
                <li>Trigger your GitHub Actions workflow</li>
                <li>You should receive Playwright test reports via email</li>
            </ul>
            <p><em>Generated by test-email.py</em></p>
        </body>
        </html>
        """
        
        html_part = MIMEText(html_content, 'html')
        msg.attach(html_part)
        
        # Connect to SMTP server
        print("🔗 Connecting to Gmail SMTP...")
        server = smtplib.SMTP(smtp_host, smtp_port)
        server.starttls()
        
        # Login
        print("🔐 Logging in...")
        server.login(username, password)
        
        # Send email
        print("📧 Sending test email...")
        server.sendmail(username, [recipient], msg.as_string())
        
        # Close connection
        server.quit()
        
        print("✅ Test email sent successfully!")
        print("📧 Check your inbox for the test email")
        print("\n🎯 Your Gmail SMTP settings are ready for GitHub Actions!")
        print("\n📋 Add these secrets to your GitHub repository:")
        print(f"EMAIL_SMTP_HOST = {smtp_host}")
        print(f"EMAIL_SMTP_PORT = {smtp_port}")
        print(f"EMAIL_USERNAME = {username}")
        print(f"EMAIL_PASSWORD = {password}")
        print(f"EMAIL_RECIPIENTS = {recipient}")
        
    except smtplib.SMTPAuthenticationError:
        print("❌ Authentication failed!")
        print("💡 Make sure you're using an App Password, not your regular Gmail password")
        print("🔗 Generate an App Password: https://myaccount.google.com/apppasswords")
        
    except smtplib.SMTPException as e:
        print(f"❌ SMTP error: {str(e)}")
        
    except Exception as e:
        print(f"❌ Unexpected error: {str(e)}")

if __name__ == "__main__":
    print("🧪 Gmail SMTP Test for GitHub Actions Email Notifications")
    print("=" * 60)
    test_gmail_smtp()
